// Auto-generated by scripts/generate-sdk-actions.py — do not edit manually.

/**
 * All valid compliance action constants for AuditRails.
 * Use these with `auditrails.log({ action: Actions.Auth.Login, ... })`.
 */
export const Actions = {
  AccessControl: {
    AccessGranted: 'access.granted',
    Revoked: 'access.revoked',
    PermissionGranted: 'permission.granted'
  },
  AssetManagement: {
    Registered: 'asset.registered'
  },
  Authentication: {
    Failed: 'auth.failed',
    Login: 'auth.login',
    Logout: 'auth.logout',
    Mfa: 'auth.mfa'
  },
  Breach: {
    Detected: 'breach.detected',
    Notified: 'breach.notified'
  },
  BusinessContinuity: {
    Completed: 'backup.completed'
  },
  ChangeManagement: {
    Approved: 'change.approved',
    Changed: 'config.changed'
  },
  Compliance: {
    Completed: 'audit.completed',
    Report: 'compliance.report'
  },
  ConfigurationManagement: {
    Completed: 'deploy.completed'
  },
  ConsentManagement: {
    Given: 'consent.given',
    Withdrawn: 'consent.withdrawn'
  },
  ConsumerRights: {
    Accessed: 'data.accessed',
    Deleted: 'data.deleted',
    Updated: 'data.updated',
    Request: 'privacy.request'
  },
  DataAccess: {
    Accessed: 'cardholder.accessed'
  },
  DataPortability: {
    Exported: 'data.exported'
  },
  DataSharing: {
    Shared: 'data.shared'
  },
  DataSubjectRights: {
    Completed: 'dsar.completed',
    Received: 'dsar.received'
  },
  Encryption: {
    Status: 'encryption.status'
  },
  Governance: {
    Completed: 'training.completed'
  },
  IncidentManagement: {
    Detected: 'incident.detected',
    Notified: 'incident.notified',
    Resolved: 'incident.resolved'
  },
  NetworkSecurity: {
    Changed: 'firewall.changed'
  },
  PhiAccess: {
    Accessed: 'phi.accessed',
    Amended: 'phi.amended',
    Disclosed: 'phi.disclosed'
  },
  Processing: {
    Started: 'processing.started',
    Stopped: 'processing.stopped'
  },
  ResilienceTesting: {
    Scan: 'vulnerability.scan'
  },
  Retention: {
    Expired: 'retention.expired'
  },
  RiskManagement: {
    Assessed: 'risk.assessed'
  },
  VulnerabilityManagement: {
    Applied: 'patch.applied'
  },
} as const;

/** Union type of all valid action strings. */
export type ComplianceAction = typeof Actions[keyof typeof Actions][keyof typeof Actions[keyof typeof Actions]];

